const products = [
  {
    id: 1,
    title: "Men's Harrington Jacket",
    price: 74.0,
    oldPrice: 100.97,
    image: require("../../assets/images/new/image10.png"),
  },
  {
    id: 2,
    title: "Max Cirro Men's Slides",
    price: 55.0,
    oldPrice: 89.99,
    image: require("../../assets/images/new/image9.png"),
  },
  {
    id: 3,
    title: "Cotton Crewneck Sweater",
    price: 45.5,
    oldPrice: 65.0,
    image: require("../../assets/images/new/image8.png"),
  },
  {
    id: 4,
    title: "Slim Fit Chino Pants",
    price: 39.99,
    oldPrice: 59.95,
    image: require("../../assets/images/new/image7.png"),
  },
  {
    id: 5,
    title: "Leather Crossbody Bag",
    price: 68.75,
    oldPrice: 85.0,
    image: require("../../assets/images/new/image6.png"),
  },
  {
    id: 6,
    title: "Running Sneakers",
    price: 79.99,
    oldPrice: 120.0,
    image: require("../../assets/images/new/image5.png"),
  },
  {
    id: 7,
    title: "Wool Blend Scarf",
    price: 29.5,
    oldPrice: 45.0,
    image: require("../../assets/images/new/image4.png"),
  },
  {
    id: 8,
    title: "Denim Jacket",
    price: 64.25,
    oldPrice: 89.99,
    image: require("../../assets/images/new/image3.png"),
  },
  {
    id: 9,
    title: "Canvas Backpack",
    price: 49.99,
    oldPrice: 75.5,
    image: require("../../assets/images/new/image2.png"),
  },
  {
    id: 10,
    title: "Aviator Sunglasses",
    price: 35.0,
    oldPrice: 59.99,
    image: require("../../assets/images/new/image.png"),
  },
];
